# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - run: yarn
    - run: yarn lint
    - run: yarn build

    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist
    - run: echo "publish here"
